[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Micah Lee <micah@micahflee.com>"]

[dependencies]
clap = "2.31.2"
hex = "0.3.1"
base64 = "0.9.0"
colored = "1.6.0"
hamming = "0.1.3"
rust-crypto = "0.2.36"
rand = "0.5.0-pre.0"
queryst = "2.0.0"
